---
title: "Big Red Data Challenge"
author: "Cole Shegan Siniawski & Lam Do"
output: html_document
date: "2023-10-20"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(ggplot2)

women_basketball <- read_csv('WBB 9-18-23_10-16-23.csv')
men_basketball <- read_csv('MBB 9-18-23_10-3-23.csv')

football <- read_csv('Football 9-12-23_10-17-23.csv')

volleyball <- read_csv('VB 9-18-23_10-9-23.csv')
```


```{r}
# Asymmetry from another method as another possible dataset to bring in

for (i in 7:length(football)) {
  football[[i]] <- as.numeric(football[[i]])
}

for (i in 7:length(men_basketball)) {
  men_basketball[[i]] <- as.numeric(men_basketball[[i]])
}

for (i in 7:length(women_basketball)) {
  women_basketball[[i]] <- as.numeric(women_basketball[[i]])
}

for (i in 7:length(volleyball)) {
  volleyball[[i]] <- as.numeric(volleyball[[i]])
}
```


```{r}
write.csv(football, "/Users/cole_sheegs/Big Red Data Challenge/Big Red Data Repo/football_data.csv")
write.csv(men_basketball, "/Users/cole_sheegs/Big Red Data Challenge/Big Red Data Repo/men_basketball_data.csv")
write.csv(women_basketball, "/Users/cole_sheegs/Big Red Data Challenge/Big Red Data Repo/women_basketball_data.csv")
write.csv(volleyball, "/Users/cole_sheegs/Big Red Data Challenge/Big Red Data Repo/volleyball_data.csv")
```


```{r}
sel_w_basketball <- women_basketball %>% select(TestId, Date, Time, `Athlete Code`, `L|R Avg. Propulsive Force`, `L|R Peak Propulsive Force`, `L|R Propulsive Impulse Index`, `L|R Avg. Landing Force`, `L|R Peak Landing Force`, `L|R Landing Impulse Index`)

sel_m_basketball <- men_basketball %>% select(TestId, Date, Time, `Athlete Code`, `L|R Avg. Propulsive Force`, `L|R Peak Propulsive Force`, `L|R Propulsive Impulse Index`, `L|R Avg. Landing Force`, `L|R Peak Landing Force`, `L|R Landing Impulse Index`)

sel_football <- football %>% select(TestId, Date, Time, `Athlete Code`, `L|R Avg. Propulsive Force`, `L|R Peak Propulsive Force`, `L|R Propulsive Impulse Index`, `L|R Avg. Landing Force`, `L|R Peak Landing Force`, `L|R Landing Impulse Index`)

sel_volleyball <- volleyball %>% select(TestId, Date, Time, `Athlete Code`, `L|R Avg. Propulsive Force`, `L|R Peak Propulsive Force`, `L|R Propulsive Impulse Index`, `L|R Avg. Landing Force`, `L|R Peak Landing Force`, `L|R Landing Impulse Index`)
```


```{r}
football <- football %>% mutate(L_R_Diff_Peak_Propulsive = abs(`Left Force at Peak Propulsive Force` - `Right Force at Peak Propulsive Force`), L_R_Total_Peak_Propulsive = `Left Force at Peak Propulsive Force` + `Right Force at Peak Propulsive Force`,  Peak_Propulsive_Asymmetry_Index = (L_R_Diff_Peak_Propulsive/L_R_Total_Peak_Propulsive) * 100)

men_basketball <- men_basketball %>% mutate(L_R_Diff_Peak_Propulsive = abs(`Left Force at Peak Propulsive Force` - `Right Force at Peak Propulsive Force`), L_R_Total_Peak_Propulsive = `Left Force at Peak Propulsive Force` + `Right Force at Peak Propulsive Force`,  Peak_Propulsive_Asymmetry_Index = (L_R_Diff_Peak_Propulsive/L_R_Total_Peak_Propulsive) * 100)

women_basketball <- women_basketball %>% mutate(L_R_Diff_Peak_Propulsive = abs(`Left Force at Peak Propulsive Force` - `Right Force at Peak Propulsive Force`), L_R_Total_Peak_Propulsive = `Left Force at Peak Propulsive Force` + `Right Force at Peak Propulsive Force`,  Peak_Propulsive_Asymmetry_Index = (L_R_Diff_Peak_Propulsive/L_R_Total_Peak_Propulsive) * 100)

volleyball <- volleyball %>% mutate(L_R_Diff_Peak_Propulsive = abs(`Left Force at Peak Propulsive Force` - `Right Force at Peak Propulsive Force`), L_R_Total_Peak_Propulsive = `Left Force at Peak Propulsive Force` + `Right Force at Peak Propulsive Force`,  Peak_Propulsive_Asymmetry_Index = (L_R_Diff_Peak_Propulsive/L_R_Total_Peak_Propulsive) * 100)
```


```{r}
football %>% group_by(`Athlete Code`) %>% summarize(mean_AI = mean(Peak_Propulsive_Asymmetry_Index))
men_basketball %>% group_by(`Athlete Code`) %>% summarize(mean_AI = mean(Peak_Propulsive_Asymmetry_Index))
women_basketball %>% group_by(`Athlete Code`) %>% summarize(mean_AI = mean(Peak_Propulsive_Asymmetry_Index))
volleyball %>% group_by(`Athlete Code`) %>% summarize(mean_AI = mean(Peak_Propulsive_Asymmetry_Index))
```


```{r}
football <- football %>% mutate(L_R_Diff_Peak_Landing = abs(`Left Force at Peak Landing Force` - `Right Force at Peak Landing Force`), L_R_Total_Peak_Landing = `Left Force at Peak Landing Force` + `Right Force at Peak Landing Force`,  Peak_Landing_Asymmetry_Index = (L_R_Diff_Peak_Landing/L_R_Total_Peak_Landing) * 100)

men_basketball <- men_basketball %>% mutate(L_R_Diff_Peak_Landing = abs(`Left Force at Peak Landing Force` - `Right Force at Peak Landing Force`), L_R_Total_Peak_Landing = `Left Force at Peak Landing Force` + `Right Force at Peak Landing Force`,  Peak_Landing_Asymmetry_Index = (L_R_Diff_Peak_Landing/L_R_Total_Peak_Landing) * 100)

women_basketball <- women_basketball %>% mutate(L_R_Diff_Peak_Landing = abs(`Left Force at Peak Landing Force` - `Right Force at Peak Landing Force`), L_R_Total_Peak_Landing = `Left Force at Peak Landing Force` + `Right Force at Peak Landing Force`,  Peak_Landing_Asymmetry_Index = (L_R_Diff_Peak_Landing/L_R_Total_Peak_Landing) * 100)

volleyball <- volleyball %>% mutate(L_R_Diff_Peak_Landing = abs(`Left Force at Peak Landing Force` - `Right Force at Peak Landing Force`), L_R_Total_Peak_Landing = `Left Force at Peak Landing Force` + `Right Force at Peak Landing Force`,  Peak_Landing_Asymmetry_Index = (L_R_Diff_Peak_Landing/L_R_Total_Peak_Landing) * 100)
```


```{r}
football %>% group_by(`Athlete Code`) %>% summarize(mean_AI = mean(Peak_Landing_Asymmetry_Index))
men_basketball %>% group_by(`Athlete Code`) %>% summarize(mean_AI = mean(Peak_Landing_Asymmetry_Index))
women_basketball %>% group_by(`Athlete Code`) %>% summarize(mean_AI = mean(Peak_Landing_Asymmetry_Index))
volleyball %>% group_by(`Athlete Code`) %>% summarize(mean_AI = mean(Peak_Landing_Asymmetry_Index))
```


```{r}
football <- football %>% mutate(L_R_Diff_Peak_Braking = abs(`Left Force at Peak Braking Force` - `Right Force at Peak Braking Force`), L_R_Total_Peak_Braking = `Left Force at Peak Landing Force` + `Right Force at Peak Landing Force`,  Peak_Braking_Asymmetry_Index = (L_R_Diff_Peak_Braking/L_R_Total_Peak_Braking) * 100)

men_basketball <- men_basketball %>% mutate(L_R_Diff_Peak_Braking = abs(`Left Force at Peak Braking Force` - `Right Force at Peak Braking Force`), L_R_Total_Peak_Braking = `Left Force at Peak Braking Force` + `Right Force at Peak Braking Force`,  Peak_Braking_Asymmetry_Index = (L_R_Diff_Peak_Braking/L_R_Total_Peak_Braking) * 100)

women_basketball <- women_basketball %>% mutate(L_R_Diff_Peak_Braking = abs(`Left Force at Peak Braking Force` - `Right Force at Peak Braking Force`), L_R_Total_Peak_Braking = `Left Force at Peak Braking Force` + `Right Force at Peak Braking Force`,  Peak_Braking_Asymmetry_Index = (L_R_Diff_Peak_Braking/L_R_Total_Peak_Braking) * 100)

volleyball <- volleyball %>% mutate(L_R_Diff_Peak_Braking = abs(`Left Force at Peak Braking Force` - `Right Force at Peak Braking Force`), L_R_Total_Peak_Braking = `Left Force at Peak Braking Force` + `Right Force at Peak Braking Force`,  Peak_Braking_Asymmetry_Index = (L_R_Diff_Peak_Braking/L_R_Total_Peak_Braking) * 100)
```


```{r}
cor.test(football$`Takeoff Velocity`, football$Peak_Landing_Asymmetry_Index)
cor.test(men_basketball$`Takeoff Velocity`, men_basketball$Peak_Landing_Asymmetry_Index)
cor.test(women_basketball$`Takeoff Velocity`, women_basketball$Peak_Landing_Asymmetry_Index)
cor.test(volleyball$`Takeoff Velocity`, volleyball$Peak_Landing_Asymmetry_Index)
```


```{r}
mean(football$`Jump Height`)
mean(men_basketball$`Jump Height`)
mean(women_basketball$`Jump Height`)
mean(volleyball$`Jump Height`)
```


```{r}
mean(football$Peak_Landing_Asymmetry_Index, na.rm = TRUE)
mean(men_basketball$Peak_Landing_Asymmetry_Index)
mean(women_basketball$Peak_Landing_Asymmetry_Index)
mean(volleyball$Peak_Landing_Asymmetry_Index)
```


```{r}
mean(football$Peak_Braking_Asymmetry_Index, na.rm = TRUE)
mean(men_basketball$Peak_Braking_Asymmetry_Index)
mean(women_basketball$Peak_Braking_Asymmetry_Index)
mean(volleyball$Peak_Braking_Asymmetry_Index)
```


```{r}
cor.test(football$`Time To Takeoff`, football$Peak_Landing_Asymmetry_Index)
cor.test(men_basketball$`Time To Takeoff`, men_basketball$Peak_Landing_Asymmetry_Index)
cor.test(women_basketball$`Time To Takeoff`, women_basketball$Peak_Landing_Asymmetry_Index)
cor.test(volleyball$`Time To Takeoff`, volleyball$Peak_Landing_Asymmetry_Index)
```


```{r}
cor.test(asb(football$``))

cor.test(abs(football$`L|R Peak Braking Force`), football$Peak_Braking_Asymmetry_Index, na.rm = TRUE)
cor.test(abs(men_basketball$`L|R Peak Braking Force`), men_basketball$Peak_Braking_Asymmetry_Index)
cor.test(abs(women_basketball$`L|R Peak Braking Force`), women_basketball$Peak_Braking_Asymmetry_Index)
cor.test(abs(volleyball$`L|R Peak Braking Force`), volleyball$Peak_Braking_Asymmetry_Index)
```


```{r}
# Football asymmetry groups

fb_less_10_perc <- football %>% filter(Peak_Landing_Asymmetry_Index < 10)
fb_middle_perc <- football %>% filter(Peak_Landing_Asymmetry_Index >= 10, Peak_Landing_Asymmetry_Index <= 15)
fb_greater_15_perc <- football %>% filter(Peak_Landing_Asymmetry_Index > 15)

mean(fb_less_10_perc$`Jump Height`)
mean(fb_middle_perc$`Jump Height`)
mean(fb_greater_15_perc$`Jump Height`)

mean(fb_less_10_perc$`Peak Propulsive Force`)
mean(fb_middle_perc$`Peak Propulsive Force`)
mean(fb_greater_15_perc$`Peak Propulsive Force`)

t.test(fb_less_10_perc$`Jump Height`, fb_middle_perc$`Jump Height`)
t.test(fb_less_10_perc$`Jump Height`, fb_greater_15_perc$`Jump Height`)
t.test(fb_middle_perc$`Jump Height`, fb_greater_15_perc$`Jump Height`)
```


```{r}
# Mens Basketball asymmetry groups

mbb_less_10_perc <- men_basketball %>% filter(Peak_Landing_Asymmetry_Index < 10)
mbb_middle_perc <- men_basketball %>% filter(Peak_Landing_Asymmetry_Index >= 10, Peak_Landing_Asymmetry_Index <= 15)
mbb_greater_15_perc <- men_basketball %>% filter(Peak_Landing_Asymmetry_Index > 15)

mean(mbb_less_10_perc$`Jump Height`)
mean(mbb_middle_perc$`Jump Height`)
mean(mbb_greater_15_perc$`Jump Height`)

mean(mbb_less_10_perc$`Peak Propulsive Force`)
mean(mbb_middle_perc$`Peak Propulsive Force`)
mean(mbb_greater_15_perc$`Peak Propulsive Force`)
```


```{r}
# Womens Basketball asymmetry groups

wbb_less_10_perc <- women_basketball %>% filter(Peak_Landing_Asymmetry_Index < 10)
wbb_middle_perc <- women_basketball %>% filter(Peak_Landing_Asymmetry_Index >= 10, Peak_Landing_Asymmetry_Index <= 15)
wbb_greater_15_perc <- women_basketball %>% filter(Peak_Landing_Asymmetry_Index > 15)

mean(wbb_less_10_perc$`Jump Height`)
mean(wbb_middle_perc$`Jump Height`)
mean(wbb_greater_15_perc$`Jump Height`)

mean(wbb_less_10_perc$`Peak Propulsive Force`)
mean(wbb_middle_perc$`Peak Propulsive Force`)
mean(wbb_greater_15_perc$`Peak Propulsive Force`)
```


```{r}
# Volleyball asymmetry groups

vb_less_10_perc <- volleyball %>% filter(Peak_Landing_Asymmetry_Index < 10)
vb_middle_perc <- volleyball %>% filter(Peak_Landing_Asymmetry_Index >= 10, Peak_Landing_Asymmetry_Index <= 15)
vb_greater_15_perc <- volleyball %>% filter(Peak_Landing_Asymmetry_Index > 15)

mean(vb_less_10_perc$`Jump Height`)
mean(vb_middle_perc$`Jump Height`)
mean(vb_greater_15_perc$`Jump Height`)

mean(vb_less_10_perc$`Peak Propulsive Force`)
mean(vb_middle_perc$`Peak Propulsive Force`)
mean(vb_greater_15_perc$`Peak Propulsive Force`)
```


L/R Peak Propulsive Force, L/R Peak Landing Force, Landing Impulse Index, Symmetry Index (High-Low)/Total*100 (%)
Asymmetry indexes over 10% may show increased disposition to ACL injury.






------------------------------------------------------------------------------------------------------------































```{r}
sel_football %>% ggplot(aes(x = `L|R Avg. Landing Force`)) + geom_histogram()
sel_football %>% ggplot(aes(x = `L|R Peak Landing Force`)) + geom_histogram()
sel_football %>% ggplot(aes(x = `L|R Landing Impulse Index`)) + geom_histogram()

sel_m_basketball %>% ggplot(aes(x = `L|R Avg. Propulsive Force`)) + geom_histogram()
sel_m_basketball %>% ggplot(aes(x = `L|R Peak Propulsive Force`)) + geom_histogram()
sel_m_basketball %>% ggplot(aes(x = `L|R Propulsive Impulse Index`)) + geom_histogram()
```


```{r}
mean(football$`L|R Peak Propulsive Force`)
mean(football$`L|R Propulsive Impulse Index`)

mean(football$`L|R Peak Landing Force`, na.rm = TRUE)
mean(football$`L|R Landing Impulse Index`, na.rm = TRUE)
```


```{r}
football %>% ggplot(aes(x = `Right Force at Peak Propulsive Force`, y = `Left Force at Peak Propulsive Force`)) + geom_point(alpha = .3) + geom_smooth(method = lm)

cor.test(football$`Right Force at Peak Propulsive Force`, football$`Left Force at Peak Propulsive Force`)

football %>% ggplot(aes(x = `Right Force at Peak Landing Force`, y = `Left Force at Peak Landing Force`)) + geom_point(alpha = .3) + geom_smooth(method = lm)

cor.test(football$`Right Force at Peak Landing Force`, football$`Left Force at Peak Landing Force`)

diff_between_cor_foot <- 0.9123277 - 0.6290015
print(diff_between_cor_foot)
```


```{r}
men_basketball %>% ggplot(aes(x = `Right Force at Peak Propulsive Force`, y = `Left Force at Peak Propulsive Force`)) + geom_point(alpha = .3) + geom_smooth(method = lm)

cor.test(men_basketball$`Right Force at Peak Propulsive Force`, men_basketball$`Left Force at Peak Propulsive Force`)

men_basketball %>% ggplot(aes(x = `Right Force at Peak Landing Force`, y = `Left Force at Peak Landing Force`)) + geom_point(alpha = .3) + geom_smooth(method = lm)

cor.test(men_basketball$`Right Force at Peak Landing Force`, men_basketball$`Left Force at Peak Landing Force`)

diff_between_cor_mbb <- 0.7938649 - 0.6468983
print(diff_between_cor_mbb)
```


```{r}
women_basketball %>% ggplot(aes(x = `Right Force at Peak Propulsive Force`, y = `Left Force at Peak Propulsive Force`)) + geom_point(alpha = .3) + geom_smooth(method = lm) + xlim(NA, 1750) + ylim(NA, 1750)

cor.test(women_basketball$`Right Force at Peak Propulsive Force`, women_basketball$`Left Force at Peak Propulsive Force`)

women_basketball %>% ggplot(aes(x = `Right Force at Peak Landing Force`, y = `Left Force at Peak Landing Force`)) + geom_point(alpha = .3) + geom_smooth(method = lm) + xlim(NA, 3500) + ylim(NA, 3500)

cor.test(women_basketball$`Right Force at Peak Landing Force`, women_basketball$`Left Force at Peak Landing Force`)

diff_between_cor_wbb <- 0.701476 - 0.5495308
print(diff_between_cor_wbb)
```


```{r}
volleyball %>% ggplot(aes(x = `Right Force at Peak Propulsive Force`, y = `Left Force at Peak Propulsive Force`)) + geom_point(alpha = .3) + geom_smooth(method = lm)

cor.test(volleyball$`Right Force at Peak Propulsive Force`, volleyball$`Left Force at Peak Propulsive Force`)

volleyball %>% ggplot(aes(x = `Right Force at Peak Landing Force`, y = `Left Force at Peak Landing Force`)) + geom_point(alpha = .3) + geom_smooth(method = lm)

cor.test(volleyball$`Right Force at Peak Landing Force`, volleyball$`Left Force at Peak Landing Force`)

diff_between_cor_volley <- 0.8798827 - -0.02561232
print(diff_between_cor_volley)
```

